-- ==========================================================
-- E-Commerce Sales & Customer Analytics
-- SQL Business Analysis
--
-- Author : Akshay Kulkarni
-- Database : SQLite
-- Dataset : Olist Brazilian E-Commerce Dataset
--
-- Description:
-- This file contains SQL queries used to analyze
-- sales performance, customer behavior, product
-- performance, seller performance, delivery metrics,
-- payment trends, and customer satisfaction.
-- ==========================================================


-- =====================================================
-- DATABASE VERIFICATION
-- =====================================================

-- View first 10 records
SELECT *
FROM ecommerce
LIMIT 10;

-- Total records
SELECT COUNT(*) AS total_records
FROM ecommerce;

-- Total columns check (View using PRAGMA)
PRAGMA table_info(ecommerce);


-- =====================================================
-- ORDER ANALYSIS
-- =====================================================

-- Total Orders
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce;

-- Order Status Distribution
SELECT
    order_status,
    COUNT(*) AS total_orders
FROM ecommerce
GROUP BY order_status
ORDER BY total_orders DESC;

SELECT DISTINCT customer_state
FROM ecommerce;

SELECT *
FROM ecommerce
LIMIT 10 OFFSET 10;

SELECT COUNT(*)
FROM ecommerce
WHERE review_comment_message IS NULL;

SELECT
    strftime('%Y', order_purchase_timestamp) AS year,
    COUNT(*) AS orders
FROM ecommerce
GROUP BY year;

-- Orders by Year
SELECT
    order_year,
    COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce
GROUP BY order_year;

-- Orders by Month
SELECT
    order_month,
    COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce
GROUP BY order_month
ORDER BY order_month;


-- =====================================================
-- REVENUE ANALYSIS
-- =====================================================
-- ==========================================================
-- Query 07
-- Business Question:
-- What is the total revenue generated by the platform?
-- ==========================================================

SELECT ROUND(SUM(price),2) AS total_revenue
FROM ecommerce;

-- Average Order Value
SELECT ROUND(AVG(price),2) AS average_order_value
FROM ecommerce;

-- Monthly Revenue
SELECT
    order_month,
    ROUND(SUM(price),2) AS revenue
FROM ecommerce
GROUP BY order_month
ORDER BY order_month;

-- Revenue by Weekday
SELECT
    purchase_weekday,
    ROUND(SUM(price),2) AS revenue
FROM ecommerce
GROUP BY purchase_weekday
ORDER BY revenue DESC;

SELECT
    customer_state,
    SUM(price) AS revenue
FROM ecommerce
GROUP BY customer_state
HAVING revenue > 100000
ORDER BY revenue DESC;


-- =====================================================
-- PRODUCT ANALYSIS
-- =====================================================
-- Top 10 Product Categories
SELECT
    product_category_name,
    ROUND(SUM(price),2) AS revenue
FROM ecommerce
GROUP BY product_category_name
ORDER BY revenue DESC
LIMIT 10;


-- Bottom 10 Product Categories
SELECT
    product_category_name,
    ROUND(SUM(price),2) AS revenue
FROM ecommerce
GROUP BY product_category_name
ORDER BY revenue
LIMIT 10;

-- Average Product Price by Category
SELECT
    product_category_name,
    ROUND(AVG(price),2) AS avg_price
FROM ecommerce
GROUP BY product_category_name
ORDER BY avg_price DESC;


-- =====================================================
-- CUSTOMER ANALYSIS
-- =====================================================
-- Top 10 Customers
SELECT
    customer_unique_id,
    ROUND(SUM(price),2) AS spending
FROM ecommerce
GROUP BY customer_unique_id
ORDER BY spending DESC
LIMIT 10;

-- Orders by State
SELECT
    customer_state,
    COUNT(DISTINCT order_id) AS orders
FROM ecommerce
GROUP BY customer_state
ORDER BY orders DESC;

-- Revenue by State
SELECT
    customer_state,
    ROUND(SUM(price),2) AS revenue
FROM ecommerce
GROUP BY customer_state
ORDER BY revenue DESC;

-- Top Cities
SELECT
    customer_city,
    COUNT(DISTINCT order_id) AS orders
FROM ecommerce
GROUP BY customer_city
ORDER BY orders DESC
LIMIT 10;

-- =====================================================
-- SELLER ANALYSIS
-- =====================================================

-- Top Sellers by Revenue
SELECT
    seller_id,
    ROUND(SUM(price),2) AS revenue
FROM ecommerce
GROUP BY seller_id
ORDER BY revenue DESC
LIMIT 10;

-- Seller Order Count
SELECT
    seller_id,
    COUNT(order_id) AS total_orders
FROM ecommerce
GROUP BY seller_id
ORDER BY total_orders DESC
LIMIT 10;



-- ==========================================================
-- PAYMENT ANALYSIS
--
-- Objective:
-- Analyze customer payment behavior,
-- preferred payment methods,
-- and installment usage.
-- ==========================================================
-- Payment Method Distribution
SELECT
    payment_type,
    COUNT(*) AS transactions
FROM ecommerce
GROUP BY payment_type;

-- Revenue by Payment Method
SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS revenue
FROM ecommerce
GROUP BY payment_type
ORDER BY revenue DESC;

-- Average Installments
SELECT
    payment_type,
    ROUND(AVG(payment_installments),2) AS avg_installments
FROM ecommerce
GROUP BY payment_type;

-- =====================================================
-- REVIEW ANALYSIS
-- =====================================================
-- Review Distribution
SELECT
    review_score,
    COUNT(*) AS total_reviews
FROM ecommerce
GROUP BY review_score
ORDER BY review_score;

-- Average Review Score
SELECT
    ROUND(AVG(review_score),2) AS average_review
FROM ecommerce;

-- Review Score by Category
SELECT
    product_category_name,
    ROUND(AVG(review_score),2) AS avg_review
FROM ecommerce
GROUP BY product_category_name
ORDER BY avg_review DESC;


-- =====================================================
-- DELIVERY ANALYSIS
-- =====================================================
-- Average Delivery Days
SELECT
    ROUND(AVG(delivery_days),2) AS avg_delivery
FROM ecommerce;

-- Average Delivery Delay
SELECT
    ROUND(AVG(delivery_delay_days),2) AS avg_delay
FROM ecommerce;

-- Average Delivery by State
SELECT
    customer_state,
    ROUND(AVG(delivery_days),2) AS avg_delivery
FROM ecommerce
GROUP BY customer_state
ORDER BY avg_delivery;


-- =====================================================
-- WINDOW FUNCTION
-- =====================================================
SELECT
    seller_id,
    ROUND(SUM(price),2) AS revenue,
    RANK() OVER(
        ORDER BY SUM(price) DESC
    ) AS seller_rank
FROM ecommerce
GROUP BY seller_id;

-- =====================================================
-- CTE
-- =====================================================
WITH category_revenue AS
(
    SELECT
        product_category_name,
        SUM(price) AS revenue
    FROM ecommerce
    GROUP BY product_category_name
)

SELECT *
FROM category_revenue
ORDER BY revenue DESC
LIMIT 10;


-- =====================================================
-- CASE WHEN
-- =====================================================
SELECT
    order_id,
    delivery_delay_days,
    CASE
        WHEN delivery_delay_days < 0 THEN 'Early'
        WHEN delivery_delay_days = 0 THEN 'On Time'
        ELSE 'Late'
    END AS delivery_status
FROM ecommerce;


-- =====================================================
-- Dense rank
-- =====================================================


SELECT
    customer_unique_id,
    SUM(price) AS spending,
    DENSE_RANK() OVER(
        ORDER BY SUM(price) DESC
    ) AS customer_rank
FROM ecommerce
GROUP BY customer_unique_id;



-- =====================================================
-- row number
-- =====================================================
SELECT
    order_id,
    customer_unique_id,
    price,
    ROW_NUMBER() OVER(
        ORDER BY price DESC
    ) AS row_num
FROM ecommerce;





-- ==========================================================
-- END OF BUSINESS SQL ANALYSIS
--
-- Total Queries : 40+
--
-- SQL Concepts Used
--
-- SELECT
-- WHERE
-- GROUP BY
-- HAVING
-- ORDER BY
-- DISTINCT
-- Aggregate Functions
-- CASE WHEN
-- CTE
-- Window Functions
-- Ranking
--
-- ==========================================================